name: Tag and publish
on:
  push:
    branches:
      - main
# Remove line 65 to enable automated semantic version bumps.
# Change line 71 from "if: false" to "if: true" to enable PyPI publishing. 
# Requires that svc-aindscicomp be added as an admin to repo.
jobs:
  tag:
    if: ${{github.event.repository.name == 'scicomp-docs'}}
    uses: AllenNeuralDynamics/aind-github-actions/.github/workflows/tag.yml@main
    secrets:
      SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}